# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rinterface}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dave Bryson", "\303\211verton Ribeiro", "Marcos Piccinini"]
  s.date = %q{2010-03-31}
  s.description = %q{Pure Ruby client that can send RPC calls to an Erlang node}
  s.email = %q{r@interf.ace}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "VERSION",
     "examples/client.rb",
     "examples/math_server.erl",
     "lib/rinterface.rb",
     "lib/rinterface/epmd.rb",
     "lib/rinterface/erl.rb",
     "lib/rinterface/erlang/decoder.rb",
     "lib/rinterface/erlang/encoder.rb",
     "lib/rinterface/erlang/external_format.rb",
     "lib/rinterface/erlang/types.rb",
     "lib/rinterface/node.rb",
     "rinterface.gemspec",
     "spec/rinterface/erl_spec.rb",
     "spec/rinterface/erlang/external_format_spec.rb",
     "spec/rinterface/node_spec.rb",
     "spec/rinterface_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_server.erl"
  ]
  s.homepage = %q{http://github.com/davebryson/rinterface}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Erlang RPC Ruby Client}
  s.test_files = [
    "spec/rinterface_spec.rb",
     "spec/spec_helper.rb",
     "spec/rinterface/node_spec.rb",
     "spec/rinterface/erl_spec.rb",
     "spec/rinterface/erlang/external_format_spec.rb",
     "examples/client.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

